### ISSUE TITLE
Reactant v0.2.172 and above fails to compile Lux model, while v0.2.171 works just fine

### ISSUE THREAD

**Issue by Sleort** [EnzymeAD/Reactant.jl#1804]
This works:
```
(jl_DYkUR1) pkg> st
Status `/tmp/jl_DYkUR1/Project.toml`
  [b2108857] Lux v1.24.0
⌃ [3c362404] Reactant v0.2.171
  [9a3f8284] Random v1.11.0
Info Packages marked with ⌃ have new versions available and may be upgradable.

julia> using Lux, Reactant, Random

julia> const xdev = reactant_device()
(::ReactantDevice{Missing, Missing, Missing, Missing}) (generic function with 1 method)

julia> model = Conv((3,3), 1=>1)
Conv((3, 3), 1 => 1)         # 10 parameters

julia> ps, st = Lux.setup(Random.default_rng(), model) |> xdev;
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1761814970.893636   36469 service.cc:158] XLA service 0x22b16d0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1761814970.893707   36469 service.cc:166]   StreamExecutor device (0): NVIDIA GeForce RTX 4070 Laptop GPU, Compute Capability 8.9
I0000 00:00:1761814970.894194   36469 se_gpu_pjrt_client.cc:1339] Using BFC allocator.
I0000 00:00:1761814970.894238   36469 gpu_helpers.cc:136] XLA backend allocating 6146408448 bytes on device 0 for BFCAllocator.
I0000 00:00:1761814970.894277   36469 gpu_helpers.cc:177] XLA backend will use up to 2048802816 bytes on device 0 for CollectiveBFCAllocator.
I0000 00:00:1761814970.907333   36469 cuda_dnn.cc:463] Loaded cuDNN version 90800

julia> x = rand(Float32, 10, 10, 1, 1) |> xdev;

julia> @jit model(x, ps, st)

(ConcretePJRTArray{Float32, 4, 1, Reactant.Sharding.ShardInfo{Reactant.Sharding.NoSharding, Nothing}}(Float32[-0.8066233 -0.7050564 … -0.9303775 -0.5120818; -0.50369656 -0.5531037 … -0.22096159 -0.49018833; … ; -0.36883602 -0.36507434 … -0.6171071 -0.87650114; -0.094239205 -0.70827335 … -0.7866802 -1.2901264;;;;]), NamedTuple())
```
... while doing the same thing with v0.2.172 fails:
```
(jl_LkoBMu) pkg> st
Status `/tmp/jl_LkoBMu/Project.toml`
  [b2108857] Lux v1.24.0
⌃ [3c362404] Reactant v0.2.172
  [9a3f8284] Random v1.11.0
Info Packages marked with ⌃ have new versions available and may be upgradable.

julia> using Lux, Reactant, Random

julia> const xdev = reactant_device()
(::ReactantDevice{Missing, Missing, Missing, Missing}) (generic function with 1 method)

julia> model = Conv((3,3), 1=>1)
Conv((3, 3), 1 => 1)         # 10 parameters

julia> ps, st = Lux.setup(Random.default_rng(), model) |> xdev;
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1761815169.294402   37037 service.cc:158] XLA service 0x1622a4b0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1761815169.294458   37037 service.cc:166]   StreamExecutor device (0): NVIDIA GeForce RTX 4070 Laptop GPU, Compute Capability 8.9
I0000 00:00:1761815169.294830   37037 se_gpu_pjrt_client.cc:770] Using BFC allocator.
I0000 00:00:1761815169.294860   37037 gpu_helpers.cc:136] XLA backend allocating 6146408448 bytes on device 0 for BFCAllocator.
I0000 00:00:1761815169.294895   37037 gpu_helpers.cc:177] XLA backend will use up to 2048802816 bytes on device 0 for CollectiveBFCAllocator.
I0000 00:00:1761815169.317817   37037 cuda_dnn.cc:463] Loaded cuDNN version 91400

julia> x = rand(Float32, 10, 10, 1, 1) |> xdev;

julia> @jit model(x, ps, st)
┌ Error: Compilation failed, MLIR module written to /tmp/reactant_QfnHPl/module_000_reactant_Conv((3..._post_xla_compile.mlir
└ @ Reactant.MLIR.IR ~/.julia/packages/Reactant/Nc0uv/src/mlir/IR/Pass.jl:119
ERROR: module @"reactant_Conv((3..." attributes {mhlo.num_partitions = 1 : i64, mhlo.num_replicas = 1 : i64} {
  func.func @main(%arg0: tensor<1x1x10x10xf32>, %arg1: tensor<1x1x3x3xf32>, %arg2: tensor<1xf32>) -> tensor<1x1x8x8xf32> {
    %0 = "mhlo.reverse"(%arg1) <{dimensions = dense<[3, 2]> : tensor<2xi64>}> : (tensor<1x1x3x3xf32>) -> tensor<1x1x3x3xf32>
    %1 = mhlo.convolution(%arg0, %0) dim_numbers = [b, f, 1, 0]x[o, i, 1, 0]->[b, f, 1, 0], window = {stride = [1, 1], pad = [[0, 0], [0, 0]], rhs_dilate = [1, 1]} {batch_group_count = 1 : i64, feature_group_count = 1 : i64, precision_config = [#mhlo<precision DEFAULT>, #mhlo<precision DEFAULT>]} : (tensor<1x1x10x10xf32>, tensor<1x1x3x3xf32>) -> tensor<1x1x8x8xf32>
    %2 = "mhlo.broadcast_in_dim"(%arg2) <{broadcast_dimensions = dense<1> : tensor<1xi64>}> : (tensor<1xf32>) -> tensor<1x1x8x8xf32>
    %3 = mhlo.add %1, %2 : tensor<1x1x8x8xf32>
    return %3 : tensor<1x1x8x8xf32>
  }
}
INTERNAL: Autotuner could not find any supported configs for HLO: %cudnn-conv-bw-input.1 = (f32[1,1,8,8]{3,2,1,0}, u8[0]{0}) custom-call(%bitcast.15, %bitcast.17), window={size=3x3 pad=2_2x2_2}, dim_labels=bf01_oi01->bf01, custom_call_target="__cudnn$convBackwardInput", backend_config={"operation_queue_id":"0","wait_on_operation_queues":[],"cudnn_conv_backend_config":{"activation_mode":"kNone","conv_result_scale":1,"side_input_scale":0,"leakyrelu_alpha":0},"force_earliest_schedule":false,"reification_cost":[],"device_type":"DEVICE_TYPE_INVALID"}

Stacktrace:
 [1] reactant_err(msg::Cstring)
   @ Reactant.XLA ~/.julia/packages/Reactant/Nc0uv/src/xla/Utils.jl:12
 [2] (::Reactant.XLA.PJRT.var"#23#24"{Bool, Vector{Int64}, Int64, Int64, Bool, Reactant.XLA.PJRT.Client, Reactant.MLIR.IR.Module, Int64})()
   @ Reactant.XLA.PJRT ~/.julia/packages/Reactant/Nc0uv/src/xla/PJRT/LoadedExecutable.jl:83
 [3] try_compile_dump_mlir(f::Reactant.XLA.PJRT.var"#23#24"{Bool, Vector{Int64}, Int64, Int64, Bool, Reactant.XLA.PJRT.Client, Reactant.MLIR.IR.Module, Int64}, mod::Reactant.MLIR.IR.Module, pm::Nothing)
   @ Reactant.MLIR.IR ~/.julia/packages/Reactant/Nc0uv/src/mlir/IR/Pass.jl:134
 [4] try_compile_dump_mlir
   @ ~/.julia/packages/Reactant/Nc0uv/src/mlir/IR/Pass.jl:129 [inlined]
 [5] #compile#22
   @ ~/.julia/packages/Reactant/Nc0uv/src/xla/PJRT/LoadedExecutable.jl:82 [inlined]
 [6] compile_xla(f::Conv{typeof(identity), Int64, Int64, Tuple{Int64, Int64}, Tuple{Int64, Int64}, NTuple{4, Int64}, Tuple{Int64, Int64}, Int64, Nothing, Nothing, Static.True, Static.False}, args::Tuple{ConcretePJRTArray{Float32, 4, 1, Reactant.Sharding.ShardInfo{…}}, @NamedTuple{weight::ConcretePJRTArray{…}, bias::ConcretePJRTArray{…}}, @NamedTuple{}}; before_xla_optimizations::Bool, client::Nothing, serializable::Bool, kwargs::@Kwargs{compile_options::CompileOptions, fn_kwargs::@NamedTuple{}})
   @ Reactant.Compiler ~/.julia/packages/Reactant/Nc0uv/src/Compiler.jl:3547
 [7] compile_xla
   @ ~/.julia/packages/Reactant/Nc0uv/src/Compiler.jl:3475 [inlined]
 [8] compile(f::Conv{…}, args::Tuple{…}; kwargs::@Kwargs{…})
   @ Reactant.Compiler ~/.julia/packages/Reactant/Nc0uv/src/Compiler.jl:3579
 [9] top-level scope
   @ ~/.julia/packages/Reactant/Nc0uv/src/Compiler.jl:2652
Some type information was truncated. Use `show(err)` to see complete types.
```
FYI:
```
julia> versioninfo()
Julia Version 1.11.7
Commit f2b3dbda30a (2025-09-08 12:10 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 22 × Intel(R) Core(TM) Ultra 7 155H
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, alderlake)
Threads: 1 default, 0 interactive, 1 GC (on 22 virtual cores)
```

**Comment by wsmoses** [comment]
should be fixed on the version I just released, give it a go (reopen if not)

**Comment by Sleort** [comment]
(I do not have permission to reopen..)

Unfortunately, the issue is not fixed:
```
(jl_yYWaow) pkg> st
Status `/tmp/jl_yYWaow/Project.toml`
  [b2108857] Lux v1.25.0
  [3c362404] Reactant v0.2.175
  [9a3f8284] Random v1.11.0

julia> using Lux, Reactant, Random

julia> const xdev = reactant_device()
(::ReactantDevice{Missing, Missing, Missing, Missing, Union{}}) (generic function with 1 method)

julia> model = Conv((3,3), 1=>1)
Conv((3, 3), 1 => 1)         # 10 parameters

julia> ps, st = Lux.setup(Random.default_rng(), model) |> xdev;
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1762030836.114764   18674 service.cc:158] XLA service 0x31ec9470 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1762030836.114803   18674 service.cc:166]   StreamExecutor device (0): NVIDIA GeForce RTX 4070 Laptop GPU, Compute Capability 8.9
I0000 00:00:1762030836.115204   18674 se_gpu_pjrt_client.cc:770] Using BFC allocator.
I0000 00:00:1762030836.115234   18674 gpu_helpers.cc:136] XLA backend allocating 6146408448 bytes on device 0 for BFCAllocator.
I0000 00:00:1762030836.115266   18674 gpu_helpers.cc:177] XLA backend will use up to 2048802816 bytes on device 0 for CollectiveBFCAllocator.
I0000 00:00:1762030836.127633   18674 cuda_dnn.cc:463] Loaded cuDNN version 91400

julia> x = rand(Float32, 10, 10, 1, 1) |> xdev;

julia> @jit model(x, ps, st)
Invalid handle. Cannot load symbol cublasLtCreate

[18674] signal 6 (-6): Aborted
in expression starting at REPL[10]:1
pthread_kill at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x70739dd18cf4)
unknown function (ip: 0x70739e87ac19)
unknown function (ip: 0x70739e879391)
unknown function (ip: 0x70739e12203d)
unknown function (ip: 0x70739de7c538)
_ZN5cudnn7backend6Engine17finalize_internalEv at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libcudnn_graph.so.9 (unknown line)
_ZN5cudnn7backend10Descriptor8finalizeEv at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libcudnn_graph.so.9 (unknown line)
_ZN5cudnn7backend12EngineConfig17finalize_internalEv at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libcudnn_graph.so.9 (unknown line)
_ZN5cudnn7backend12EngcfgTmpVar7Results23emplace_back_on_successEONS0_12EngineConfigERNS1_10ErrorStackE at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libcudnn_graph.so.9 (unknown line)
_ZNK5cudnn7backend16EngineHeuristics12get_internalE27cudnnBackendAttributeName_t27cudnnBackendAttributeType_tlPlPv at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libcudnn_graph.so.9 (unknown line)
cudnnBackendGetAttribute at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libcudnn_graph.so.9 (unknown line)
_ZN14cudnn_frontend19EngineHeuristics_v815getEngineConfigEl at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN14cudnn_frontendL24get_heuristics_list_implE22cudnnBackendHeurMode_tRNS_17OperationGraph_v8ESt8functionIFbPvEEiRSt6vectorISt10shared_ptrINS_20OpaqueBackendPointerEESaISA_EES8_IKNS_16DevicePropertiesEE at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN14cudnn_frontendL19get_heuristics_listERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS6_EERNS_17OperationGraph_v8ESt8functionIFbPvEERS0_ISt10shared_ptrINS_20OpaqueBackendPointerEESaISJ_EEbiSH_IKNS_16DevicePropertiesEE at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN14cudnn_frontend19get_heuristics_listILm1EEESt6vectorI13cudnnStatus_tSaIS2_EESt5arrayINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEXT_EERNS_17OperationGraph_v8ESt8functionIFbPvEERS1_ISt10shared_ptrINS_20OpaqueBackendPointerEESaISL_EEb at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN15stream_executor3gpu12CudnnSupport18GetConvolveRunnersENS_3dnn15ConvolutionKindENS2_8DataTypeES4_PNS_6StreamERKNS2_15BatchDescriptorENS_16DeviceMemoryBaseERKNS2_16FilterDescriptorESA_S9_SA_RKNS2_21ConvolutionDescriptorEbPNS_16ScratchAllocatorERKNS_14NumericOptionsEPSt6vectorISt10unique_ptrIKNS2_8OpRunnerIFvSA_SA_SA_EEESt14default_deleteISR_EESaISU_EE at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN3xla3gpu12_GLOBAL__N_113GetAlgorithmsEPN15stream_executor3dnn10DnnSupportENS3_15ConvolutionKindENS3_8DataTypeES7_PNS2_6StreamERKNS0_13GpuConvConfigERKNS2_14NumericOptionsEb at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN3xla3gpu12CudnnBackend19GetSupportedConfigsERKNS_14HloInstructionE at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN3xla9Autotuner19GetSupportedConfigsEPNS_14HloInstructionE at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN3xla9Autotuner14TuneBestConfigEPNS_14HloInstructionE at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN3xla9Autotuner9GetConfigEPNS_14HloInstructionE at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN3xla9Autotuner8AutotuneEPNS_9HloModuleERKN4absl12lts_2025081411FunctionRefIFbRKNS_14HloInstructionEEEE at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN3xla3gpu13AutotunerPass3RunEPNS_9HloModuleERKN4absl12lts_2025081413flat_hash_setISt17basic_string_viewIcSt11char_traitsIcEENS5_18container_internal10StringHashENSB_8StringEqESaISA_EEE at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN3xla15HloPassPipeline9RunHelperIPNS_9HloModuleEEEN4absl12lts_202508148StatusOrIbEEPNS_16HloPassInterfaceET_RKNS5_13flat_hash_setISt17basic_string_viewIcSt11char_traitsIcEENS5_18container_internal10StringHashENSG_8StringEqESaISF_EEE at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN3xla15HloPassPipeline17RunPassesInternalIPNS_9HloModuleEEEN4absl12lts_202508148StatusOrIbEET_RKNS_12DebugOptionsERKNS5_13flat_hash_setISt17basic_string_viewIcSt11char_traitsIcEENS5_18container_internal10StringHashENSH_8StringEqESaISG_EEE at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN3xla15HloPassPipeline3RunEPNS_9HloModuleERKN4absl12lts_2025081413flat_hash_setISt17basic_string_viewIcSt11char_traitsIcEENS4_18container_internal10StringHashENSA_8StringEqESaIS9_EEE at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN3xla3gpu11GpuCompiler31OptimizeHloPostLayoutAssignmentEPNS_9HloModuleEPN15stream_executor14StreamExecutorERKNS_8Compiler14CompileOptionsERKNS7_12TargetConfigEPKNS0_12GpuAliasInfoEPN3tsl6thread10ThreadPoolE at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN3xla3gpu13NVPTXCompiler31OptimizeHloPostLayoutAssignmentEPNS_9HloModuleEPN15stream_executor14StreamExecutorERKNS_8Compiler14CompileOptionsERKNS7_12TargetConfigEPKNS0_12GpuAliasInfoEPN3tsl6thread10ThreadPoolE at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN3xla3gpu11GpuCompiler17OptimizeHloModuleEPNS_9HloModuleEPN15stream_executor14StreamExecutorERKNS_8Compiler14CompileOptionsERKNS7_12TargetConfigEPKNS0_12GpuAliasInfoE at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN3xla3gpu11GpuCompiler12RunHloPassesESt10unique_ptrINS_9HloModuleESt14default_deleteIS3_EEPN15stream_executor14StreamExecutorERKNS_8Compiler14CompileOptionsE at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN3xla7Service15BuildExecutableERKNS_14HloModuleProtoESt10unique_ptrINS_15HloModuleConfigESt14default_deleteIS5_EEPNS_7BackendEPN15stream_executor14StreamExecutorERKNS_8Compiler14CompileOptionsEb at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN3xla12LocalService18CompileExecutablesERKNS_14XlaComputationEN4absl12lts_202508144SpanIKPKNS_5ShapeEEERKNS_22ExecutableBuildOptionsE at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN3xla11LocalClient7CompileERKNS_14XlaComputationEN4absl12lts_202508144SpanIKPKNS_5ShapeEEERKNS_22ExecutableBuildOptionsE at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN3xla24PjRtStreamExecutorClient15CompileInternalERKNS_14XlaComputationERKSt6vectorIPKNS_5ShapeESaIS7_EESt8functionIFN4absl12lts_202508148StatusOrISt4pairIS4_IS5_SaIS5_EES5_EEERKNS_9HloModuleEEENS_14CompileOptionsEb at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN3xla24PjRtStreamExecutorClient7CompileEN4mlir8ModuleOpENS_14CompileOptionsEb at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN3xla24PjRtStreamExecutorClient14CompileAndLoadEN4mlir8ModuleOpENS_14CompileOptionsE at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
_ZN3xla23StreamExecutorGpuClient14CompileAndLoadEN4mlir8ModuleOpENS_14CompileOptionsE at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
ClientCompile at /home/a46632/.julia/artifacts/7743cf17a9e109c05ece32bfa37b0b072e04bab3/lib/libReactantExtra.so (unknown line)
#23 at /home/a46632/.julia/packages/Reactant/rauLT/src/xla/PJRT/LoadedExecutable.jl:83
try_compile_dump_mlir at /home/a46632/.julia/packages/Reactant/rauLT/src/mlir/IR/Pass.jl:134
try_compile_dump_mlir at /home/a46632/.julia/packages/Reactant/rauLT/src/mlir/IR/Pass.jl:129 [inlined]
#compile#22 at /home/a46632/.julia/packages/Reactant/rauLT/src/xla/PJRT/LoadedExecutable.jl:82 [inlined]
compile at /home/a46632/.julia/packages/Reactant/rauLT/src/xla/PJRT/LoadedExecutable.jl:68
jfptr_compile_37372 at /home/a46632/.julia/compiled/v1.11/Reactant/p9PzF_pBMVz.so (unknown line)
#compile_xla#58 at /home/a46632/.julia/packages/Reactant/rauLT/src/Compiler.jl:3565
compile_xla at /home/a46632/.julia/packages/Reactant/rauLT/src/Compiler.jl:3493 [inlined]
#compile#59 at /home/a46632/.julia/packages/Reactant/rauLT/src/Compiler.jl:3597
compile at /home/a46632/.julia/packages/Reactant/rauLT/src/Compiler.jl:3594
unknown function (ip: 0x70753153c4bd)
jl_apply at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/src/julia.h:2157 [inlined]
do_call at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/src/interpreter.c:126
eval_value at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/src/interpreter.c:223
eval_stmt_value at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/src/interpreter.c:174 [inlined]
eval_body at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/src/interpreter.c:666
jl_interpret_toplevel_thunk at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/src/interpreter.c:824
jl_toplevel_eval_flex at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/src/toplevel.c:943
jl_toplevel_eval_flex at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/src/toplevel.c:886
jl_toplevel_eval_flex at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/src/toplevel.c:886
jl_toplevel_eval_flex at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/src/toplevel.c:886
ijl_toplevel_eval_in at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/src/toplevel.c:994
eval at ./boot.jl:430 [inlined]
eval_user_input at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:261
repl_backend_loop at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:368
#start_repl_backend#59 at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:343
start_repl_backend at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:340
#run_repl#76 at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:500
run_repl at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/usr/share/julia/stdlib/v1.11/REPL/src/REPL.jl:486
jfptr_run_repl_10226.1 at /home/a46632/.julia/juliaup/julia-1.11.7+0.x64.linux.gnu/share/julia/compiled/v1.11/REPL/u0gqU_XvZAg.so (unknown line)
#1150 at ./client.jl:446
jfptr_YY.1150_14873.1 at /home/a46632/.julia/juliaup/julia-1.11.7+0.x64.linux.gnu/share/julia/compiled/v1.11/REPL/u0gqU_XvZAg.so (unknown line)
jl_apply at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/src/julia.h:2157 [inlined]
jl_f__call_latest at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/src/builtins.c:875
#invokelatest#2 at ./essentials.jl:1055 [inlined]
invokelatest at ./essentials.jl:1052 [inlined]
run_main_repl at ./client.jl:430
repl_main at ./client.jl:567 [inlined]
_start at ./client.jl:541
jfptr__start_73684.1 at /home/a46632/.julia/juliaup/julia-1.11.7+0.x64.linux.gnu/lib/julia/sys.so (unknown line)
jl_apply at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/src/julia.h:2157 [inlined]
true_main at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/src/jlapi.c:900
jl_repl_entrypoint at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/src/jlapi.c:1059
main at /cache/build/builder-demeter6-3/julialang/julia-release-1-dot-11/cli/loader_exe.c:58
unknown function (ip: 0x70753842a1c9)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x4010b8)
Allocations: 76635241 (Pool: 76629815; Big: 5426); GC: 62
Aborted (core dumped)
a46632@HI-16106:~$ 
```

**Comment by wsmoses** [comment]
Hm can you share your Julia, GPU, and other system setup?

Just because I failed to reproduce this (and ci seems fine presently)

**Comment by Sleort** [comment]
Strange...

Julia information:
```
julia> versioninfo()
Julia Version 1.11.7
Commit f2b3dbda30a (2025-09-08 12:10 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 22 × Intel(R) Core(TM) Ultra 7 155H
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, alderlake)
Threads: 1 default, 0 interactive, 1 GC (on 22 virtual cores)
```
I am using an HP ZBook Studio 16 inch G11 Mobile Workstation PC with a NVIDIA GeForce RTX 4070 Laptop GPU. `$nvidia-smi` says
```
| NVIDIA-SMI 570.195.03             Driver Version: 570.195.03     CUDA Version: 12.8     |
```
Intel Core Ultra 7 155H × 22 processor. 64 GB RAM. I am using Ubuntu 24.04.2 LTS.

Any other information that could be useful?

**Comment by Sleort** [comment]
The trick was to upgrade the Nvidia driver. With this:
```
| NVIDIA-SMI 580.95.05              Driver Version: 580.95.05      CUDA Version: 13.0     |
```
it seems to work. 🙂
